name: Hello Workflow

on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Hello
        run: |
          ls -la
          echo "KDTEST: ${{ env.KDTEST }}"
          env
