name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Hello
        run: |
          echo "Hello from GitHub Actions on a self-hosted runner!"
